<?xml version="1.0"?>
<!-- Abstract: converts Eclipse TOC in a static HTML table of content         -->
<!-- See http://www-106.ibm.com/developerworks/opensource/library/os-echelp/  -->
<!-- Changes:                                                                 -->
<!--          added book.css stylesheet, target=main                          -->
<!--          imported dynamic outline Javascript as generated by FrontPage   -->
<!-- Problem: each ul tag should look like "ul dynamicoutline", done with sed -->
<xsl:stylesheet version="1.1" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" indent="no" encoding="ISO-8859-1"/>
	<xsl:template match="toc">
		<html>
			<head>
				<link rel="stylesheet" href="css/book.css" charset="ISO-8859-1" type="text/css"/>
				<script LANGUAGE="JavaScript" SRC="fp.js" FPTYPE="dynamicoutline"/>
			</head>
			<body onclick="dynOutline()">
				<h1>
					<xsl:value-of select="@label"/>
				</h1>
				<br/>
				<ul>
					<xsl:apply-templates/>
				</ul>
			</body>
		</html>
	</xsl:template>
	<xsl:template match="topic">
		<li>
			<xsl:choose>
				<xsl:when test="@href">
					<!-- Only add a hyperlink when there is something to link to -->
					<xsl:element name="a">
						<xsl:attribute name="href"><xsl:value-of select="@href"/></xsl:attribute>
						<xsl:attribute name="target">main</xsl:attribute>
						<xsl:value-of select="@label"/>
					</xsl:element>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="@label"/>
				</xsl:otherwise>
			</xsl:choose>
			<!-- If there are any nested topics, then start a new sub-list -->
			<xsl:if test="descendant::topic">
				<ul>
					<xsl:apply-templates/>
				</ul>
			</xsl:if>
		</li>
	</xsl:template>
</xsl:stylesheet>
